<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Visiteur extends \App\Entity\Visiteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visMatricule', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visLogin', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visNom', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visPrenom', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visAdresse', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visCp', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visVille', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visDateembauche', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visPassword', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visSalt', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'secCode', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'labCode', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'Roles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visMatricule', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visLogin', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visNom', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visPrenom', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visAdresse', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visCp', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visVille', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visDateembauche', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visPassword', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'visSalt', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'secCode', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'labCode', '' . "\0" . 'App\\Entity\\Visiteur' . "\0" . 'Roles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Visiteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getVisMatricule(): ?string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getVisMatricule();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisMatricule', []);

        return parent::getVisMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisLogin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisLogin', []);

        return parent::getVisLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisLogin(string $visLogin): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisLogin', [$visLogin]);

        return parent::setVisLogin($visLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisNom', []);

        return parent::getVisNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisNom(?string $visNom): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisNom', [$visNom]);

        return parent::setVisNom($visNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisPrenom', []);

        return parent::getVisPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisPrenom(?string $visPrenom): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisPrenom', [$visPrenom]);

        return parent::setVisPrenom($visPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisAdresse', []);

        return parent::getVisAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisAdresse(?string $visAdresse): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisAdresse', [$visAdresse]);

        return parent::setVisAdresse($visAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisCp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisCp', []);

        return parent::getVisCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisCp(?string $visCp): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisCp', [$visCp]);

        return parent::setVisCp($visCp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisVille', []);

        return parent::getVisVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisVille(?string $visVille): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisVille', [$visVille]);

        return parent::setVisVille($visVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisDateembauche(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisDateembauche', []);

        return parent::getVisDateembauche();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisDateembaucheStr(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisDateembaucheStr', []);

        return parent::getVisDateembaucheStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisDateembauche(?\DateTime $visDateembauche): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisDateembauche', [$visDateembauche]);

        return parent::setVisDateembauche($visDateembauche);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisPassword', []);

        return parent::getVisPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisPassword(string $visPassword): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisPassword', [$visPassword]);

        return parent::setVisPassword($visPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisSalt', []);

        return parent::getVisSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisSalt(string $visSalt): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisSalt', [$visSalt]);

        return parent::setVisSalt($visSalt);
    }

    /**
     * {@inheritDoc}
     */
    public function setSecCode(?string $secCode): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecCode', [$secCode]);

        return parent::setSecCode($secCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setLabCode(string $labCode): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabCode', [$labCode]);

        return parent::setLabCode($labCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabCode', []);

        return parent::getLabCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getSecCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecCode', []);

        return parent::getSecCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(?string $Roles): \App\Entity\Visiteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$Roles]);

        return parent::setRoles($Roles);
    }

}
