index:
    path: /
    controller: App\Controller\MainController::addAction


    
praticien:
    path: /praticien
    controller: App\Controller\triePraticienController::triePrat
    
#triePraticien:
    #path: /triePraticien/{type}
    #controller: App\Controller\triePraticienController::triePraticien

    
medicament:
    path: /medicament
    controller: App\Controller\MainController::addAction2

    