index:
    path: /
    controller: App\Controller\MainController::addAction

praticien:
    path: /praticien
    controller: App\Controller\MainController::addAction
    
medicament:
    path: /medicament
    controller: App\Controller\MainController::addAction2
