index:
    path: /
    controller: App\Controller\MainController::main

accueil:
    path: /accueil
    controller: App\Controller\MainController::main
    
praticien:
    path: /praticien
    controller: App\Controller\triePraticienController::triePrat

medicament:
    path: /medicament
    controller: App\Controller\trieMedocController::trieMedoc