index:
    path: /
    controller: App\Controller\Admin\AdminVisiteursController::index

praticien:
    path: /praticien
    controller: App\Controller\PraticienController::index
    
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
#VISITEURS#########################################################################################################
admin:
    path: /admin
    controller: App\Controller\AdminIndexController::index

admin.visiteurs:
    path: /admin/visiteur
    controller: App\Controller\Admin\AdminVisiteursController::index

    
del.visiteurs:
    path: /admin/del_vis/{id}
    controller: App\Controller\Admin\AdminVisiteursController::delete

    
edit.visiteurs:
    path: /admin/edit_vis/{id}
    controller: App\Controller\Admin\AdminVisiteursController::edit


new.visiteurs:
    path: /admin/new_vis
    controller: App\Controller\Admin\AdminVisiteursController::new