<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVmib1d8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVmib1d8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVmib1d8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVmib1d8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVmib1d8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Vmib1d8',
    'container.build_id' => '82848dfb',
    'container.build_time' => 1553764574,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVmib1d8');
